from django.db import models


class Sofifa(models.Model):
    player_id = models.CharField(primary_key=True, max_length=20)
    player_url = models.CharField(max_length=255)
    fifa_version = models.CharField(max_length=4)
    fifa_update = models.CharField(max_length=4, blank=True, null=True)
    fifa_update_date = models.DateField(blank=True, null=True)
    short_name = models.CharField(max_length=100)
    long_name = models.CharField(max_length=255)
    player_positions = models.CharField(max_length=25)
    overall = models.FloatField(blank=True, null=True)
    potential = models.FloatField(blank=True, null=True)
    value_eur = models.TextField(blank=True, null=True)  # This field type is a guess.
    wage_eur = models.TextField(blank=True, null=True)  # This field type is a guess.
    age = models.FloatField(blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    height_cm = models.FloatField(blank=True, null=True)
    weight_kg = models.FloatField(blank=True, null=True)
    league_id = models.FloatField(blank=True, null=True)
    league_name = models.CharField(max_length=255, blank=True, null=True)
    league_level = models.CharField(max_length=4, blank=True, null=True)
    club_team_id = models.FloatField(blank=True, null=True)
    club_name = models.CharField(max_length=255, blank=True, null=True)
    club_position = models.CharField(max_length=10, blank=True, null=True)
    club_jersey_number = models.CharField(max_length=4, blank=True, null=True)
    club_loaned_from = models.CharField(max_length=255, blank=True, null=True)
    club_joined_date = models.DateField(blank=True, null=True)
    club_contract_valid_until_year = models.CharField(max_length=6, blank=True, null=True)
    nationality_id = models.CharField(max_length=5, blank=True, null=True)
    nationality_name = models.CharField(max_length=100, blank=True, null=True)
    nation_team_id = models.FloatField(blank=True, null=True)
    nation_position = models.CharField(max_length=4, blank=True, null=True)
    nation_jersey_number = models.CharField(max_length=4, blank=True, null=True)
    preferred_foot = models.CharField(max_length=5, blank=True, null=True)
    weak_foot = models.CharField(max_length=3, blank=True, null=True)
    skill_moves = models.CharField(max_length=3, blank=True, null=True)
    international_reputation = models.CharField(max_length=3, blank=True, null=True)
    work_rate = models.CharField(max_length=25, blank=True, null=True)
    body_type = models.CharField(max_length=25, blank=True, null=True)
    real_face = models.CharField(max_length=5, blank=True, null=True)
    release_clause_eur = models.TextField(blank=True, null=True)  # This field type is a guess.
    player_tags = models.CharField(max_length=255, blank=True, null=True)
    player_traits = models.CharField(max_length=255, blank=True, null=True)
    pace = models.CharField(max_length=4, blank=True, null=True)
    shooting = models.CharField(max_length=4, blank=True, null=True)
    passing = models.CharField(max_length=4, blank=True, null=True)
    dribbling = models.CharField(max_length=4, blank=True, null=True)
    defending = models.CharField(max_length=4, blank=True, null=True)
    physic = models.CharField(max_length=4, blank=True, null=True)
    attacking_crossing = models.CharField(max_length=4, blank=True, null=True)
    attacking_finishing = models.CharField(max_length=4, blank=True, null=True)
    attacking_heading_accuracy = models.CharField(max_length=4, blank=True, null=True)
    attacking_short_passing = models.CharField(max_length=4, blank=True, null=True)
    attacking_volleys = models.CharField(max_length=4, blank=True, null=True)
    skill_dribbling = models.CharField(max_length=4, blank=True, null=True)
    skill_curve = models.CharField(max_length=4, blank=True, null=True)
    skill_fk_accuracy = models.CharField(max_length=4, blank=True, null=True)
    skill_long_passing = models.CharField(max_length=4, blank=True, null=True)
    skill_ball_control = models.CharField(max_length=4, blank=True, null=True)
    movement_acceleration = models.CharField(max_length=4, blank=True, null=True)
    movement_sprint_speed = models.CharField(max_length=4, blank=True, null=True)
    movement_agility = models.CharField(max_length=4, blank=True, null=True)
    movement_reactions = models.CharField(max_length=4, blank=True, null=True)
    movement_balance = models.CharField(max_length=4, blank=True, null=True)
    power_shot_power = models.CharField(max_length=4, blank=True, null=True)
    power_jumping = models.CharField(max_length=4, blank=True, null=True)
    power_stamina = models.CharField(max_length=4, blank=True, null=True)
    power_strength = models.CharField(max_length=4, blank=True, null=True)
    power_long_shots = models.CharField(max_length=4, blank=True, null=True)
    mentality_aggression = models.CharField(max_length=4, blank=True, null=True)
    mentality_interceptions = models.CharField(max_length=4, blank=True, null=True)
    mentality_positioning = models.CharField(max_length=4, blank=True, null=True)
    mentality_vision = models.CharField(max_length=4, blank=True, null=True)
    mentality_penalties = models.CharField(max_length=4, blank=True, null=True)
    mentality_composure = models.CharField(max_length=4, blank=True, null=True)
    defending_marking_awareness = models.CharField(max_length=4, blank=True, null=True)
    defending_standing_tackle = models.CharField(max_length=4, blank=True, null=True)
    defending_sliding_tackle = models.CharField(max_length=4, blank=True, null=True)
    goalkeeping_diving = models.CharField(max_length=4, blank=True, null=True)
    goalkeeping_handling = models.CharField(max_length=4, blank=True, null=True)
    goalkeeping_kicking = models.CharField(max_length=4, blank=True, null=True)
    goalkeeping_positioning = models.CharField(max_length=4, blank=True, null=True)
    goalkeeping_reflexes = models.CharField(max_length=4, blank=True, null=True)
    goalkeeping_speed = models.CharField(max_length=4, blank=True, null=True)
    ls = models.CharField(max_length=5, blank=True, null=True)
    st = models.CharField(max_length=5, blank=True, null=True)
    rs = models.CharField(max_length=5, blank=True, null=True)
    lw = models.CharField(max_length=5, blank=True, null=True)
    lf = models.CharField(max_length=5, blank=True, null=True)
    cf = models.CharField(max_length=5, blank=True, null=True)
    rf = models.CharField(max_length=5, blank=True, null=True)
    rw = models.CharField(max_length=5, blank=True, null=True)
    lam = models.CharField(max_length=5, blank=True, null=True)
    cam = models.CharField(max_length=5, blank=True, null=True)
    ram = models.CharField(max_length=5, blank=True, null=True)
    lm = models.CharField(max_length=5, blank=True, null=True)
    lcm = models.CharField(max_length=5, blank=True, null=True)
    cm = models.CharField(max_length=5, blank=True, null=True)
    rcm = models.CharField(max_length=5, blank=True, null=True)
    rm = models.CharField(max_length=5, blank=True, null=True)
    lwb = models.CharField(max_length=5, blank=True, null=True)
    ldm = models.CharField(max_length=5, blank=True, null=True)
    cdm = models.CharField(max_length=5, blank=True, null=True)
    rdm = models.CharField(max_length=5, blank=True, null=True)
    rwb = models.CharField(max_length=5, blank=True, null=True)
    lb = models.CharField(max_length=5, blank=True, null=True)
    lcb = models.CharField(max_length=5, blank=True, null=True)
    cb = models.CharField(max_length=5, blank=True, null=True)
    rcb = models.CharField(max_length=5, blank=True, null=True)
    rb = models.CharField(max_length=5, blank=True, null=True)
    gk = models.CharField(max_length=5, blank=True, null=True)
    player_face_url = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'sofifa'

# Create your models here.

# Create your models here.
